// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjzAThYoz2GJXgvJODqMi73643ypdnPEI',
    appId: '1:89372462829:web:2ee01e4766acaeb46c06e4',
    messagingSenderId: '89372462829',
    projectId: 'vibe-guard-1c07d',
    authDomain: 'vibe-guard-1c07d.firebaseapp.com',
    storageBucket: 'vibe-guard-1c07d.firebasestorage.app',
    measurementId: 'G-CTHBF10CC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTXNND3a8mCKeeVRKl6C0RHgfHQ9ETTw',
    appId: '1:89372462829:android:6bdd3a51e1c6d6c56c06e4',
    messagingSenderId: '89372462829',
    projectId: 'vibe-guard-1c07d',
    storageBucket: 'vibe-guard-1c07d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACVzgxkqWOif45UIDNC91ISkeEHHSOwg',
    appId: '1:89372462829:ios:804358f433eab7ae6c06e4',
    messagingSenderId: '89372462829',
    projectId: 'vibe-guard-1c07d',
    storageBucket: 'vibe-guard-1c07d.firebasestorage.app',
    iosBundleId: 'com.example.vibeGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACVzgxkqWOif45UIDNC91ISkeEHHSOwg',
    appId: '1:89372462829:ios:804358f433eab7ae6c06e4',
    messagingSenderId: '89372462829',
    projectId: 'vibe-guard-1c07d',
    storageBucket: 'vibe-guard-1c07d.firebasestorage.app',
    iosBundleId: 'com.example.vibeGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjzAThYoz2GJXgvJODqMi73643ypdnPEI',
    appId: '1:89372462829:web:7614469d6891950b6c06e4',
    messagingSenderId: '89372462829',
    projectId: 'vibe-guard-1c07d',
    authDomain: 'vibe-guard-1c07d.firebaseapp.com',
    storageBucket: 'vibe-guard-1c07d.firebasestorage.app',
    measurementId: 'G-ZLP41ML7GD',
  );
}
